<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class NursingCensusReport extends Model
{
    protected $fillable = [
        'shift',
        'datereporting',
        'name_kj',
        'male',
        'female',
        'paeds_male',
        'paeds_female',
        'non_covid_new_admission',
        'non_covid_step_up',
        'non_covid_discharged',
        'non_covid_death',
        'male_ward',
        'female_ward',
        'maternity_ward',
        'children_ward',
        'male_tb_ward',
        'female_tb_ward',
        'acute_ward',
        'covid_new_admission',
        'covid_step_up',
        'covid_discharged',
        'covid_death',
        'covid_home_q',
        'covid_male',
        'covid_female',
        'covid_paeds_male',
        'covid_paeds_female',
        'covid_local',
        'covid_non_local',
        'stage_1',
        'stage_2',
        'stage_3',
        'stage_4',
        'stage_5',
        'stage_1_1',
        'stage_1_2',
        'stage_2_1',
        'stage_2_2',
        'stage_3_1',
        'stage_3_2',
        'stage_4_1',
        'stage_4_2',
        'stage_5_1',
        'stage_5_2',
        'new_stage_1',
        'new_stage_2',
        'new_stage_3',
        'new_stage_4',
        'new_stage_5',
        'pui_adult_male',
        'pui_adult_female',
        'pui_paeds_male',
        'pui_paeds_female',
        'pui_new',
        'pui_discharged',
        'pui_step_up',
        'pui_death',
        'sari_adult_male',
        'sari_adult_female',
        'sari_paeds_male',
        'sari_paeds_female',
        'sari_new',
        'sari_discharged',
        'sari_step_up',
        'sari_death',
        'staff',
        'total',
        'bor',
        'notes',
       'o2_conc',
       'o2_conc_occupied',
       'o2_cylinder',
       'o2_cylinder_occupied',
       'covid_pending',
    
        ];
}
